admin_categories_index:
    path:     /
    defaults: { _controller: "MyAppPIBundle:CategoriesAdmin:index" }
    methods:  GET

admin_categories_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppPIBundle:CategoriesAdmin:show" }
    methods:  GET

admin_categories_new:
    path:     /new
    defaults: { _controller: "MyAppPIBundle:CategoriesAdmin:new" }
    methods:  [GET, POST]

admin_categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppPIBundle:CategoriesAdmin:edit" }
    methods:  [GET, POST]

admin_categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppPIBundle:CategoriesAdmin:delete" }
    methods:  DELETE
