adminCommande:
    path:  /
    defaults: { _controller: MyAppPIBundle:CommandesAdmin:commandes }

adminShowFacture:
    path:  /facture/{id}
    defaults: { _controller: MyAppPIBundle:CommandesAdmin:showFacture }