supprimer:
    path:  /supprimer/{id}
    defaults: { _controller: MyAppPIBundle:Panier:supprimer }
ajouter:
    path:  /ajouter/{id}
    defaults: { _controller: MyAppPIBundle:Panier:ajouter }
validation:
    path:  /validation
    defaults: { _controller: MyAppPIBundle:Panier:validation }
panier:
    path:  /
    defaults: { _controller: MyAppPIBundle:Panier:panier }
livraison:
    path:  /livraison
    defaults: { _controller: MyAppPIBundle:Panier:livraison }
livraisonAdresseSuppression:
    path:  /livraison/adresse/suppression/{id}
    defaults: { _controller: MyAppPIBundle:Panier:adresseSuppression }