<?php

namespace TGSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends EntityRepository
{
}
