<?php

namespace TGSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateursAdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
}
