<?php

namespace MyApp\FourumBundle\Repository;

/**
 * deslikeLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class deslikeLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
