<?php

namespace MyApp\FourumBundle\Repository;

/**
 * LikeDeslikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeDeslikeRepository extends \Doctrine\ORM\EntityRepository
{
}
