<?php

namespace MyApp\FourumBundle\Repository;

/**
 * LikeDslikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeDslikeRepository extends \Doctrine\ORM\EntityRepository
{
}
