services:
    tva:
        class: MyApp\PIBundle\Twig\Extension\TvaExtension
        tags:
            - { name: twig.extension }
    montantTva:
          class: MyApp\PIBundle\Twig\Extension\MontantTvaExtension
          tags:
            - { name: twig.extension }
    redirectionListener:
          class: MyApp\PIBundle\Listener\RedirectionListener
          arguments: ['@service_container', '@session']
          tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    app.search:
        class: MyApp\PIBundle\Form\RechercheType
        tags:
            - { name: form.type }
    setNewReference:
          class: MyApp\PIBundle\Services\GetReference
          arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']
    setNewFacture:
          class: MyApp\PIBundle\Services\GetFacture
          arguments: ['@service_container']