<?php

namespace MyApp\PIBundle\Repository;

/**
 * ServeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServeurRepository extends \Doctrine\ORM\EntityRepository
{
//    public function byCategorie($categorie)
//    {
//         $qb = $this->createQueryBuilder('u')
//                    ->select('u')
//                    ->where('u.categorie = :categorie')
//                    ->andWhere('u.disponible = 1')
//                    ->orderBy('u.id')
//                    ->setParameter('categorie', $categorie);
//        return $qb->getQuery()->getResult();
//    }

    public function rechercheServeur($chaine)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.nom like :chaine')
                    ->orderBy('u.id')
                    ->setParameter('chaine', $chaine.'%');
        return $qb->getQuery()->getResult();
    }

//    public function findArray($array)
//    {
//         $qb = $this->createQueryBuilder('u')
//                    ->Select('u')
//                    ->Where('u.id IN (:array)')
//                    ->setParameter('array', $array);
//        return $qb->getQuery()->getResult();
//    }
}
